### ISSUE TITLE
A question about mixed signal filtering

### ISSUE THREAD

**Issue by fhrgithub** [aignacio/iir_filter#1]
I've got a problem.
I used your filter parameters, but changed the input signal to a superposition of 2K and 6K sine signals.
![image](https://user-images.githubusercontent.com/50169019/123548199-638a3400-d796-11eb-9f97-7cbafa72aa61.png)

The results on Matlab are fine,but the results on Quartus were unexpected.
![image](https://user-images.githubusercontent.com/50169019/123548216-700e8c80-d796-11eb-8f92-349d464f6e83.png)
I know little about IIR, could you give me some help?

**Comment by aignacio** [comment]
Check if your input signal is sampled in the same freq. as the filter Fs : 48000 Samples/s.

**Comment by fhrgithub** [comment]
I'm sure about that. I used your .m file to generate input signal.
```
% filter specifications
fs = 48000; % sampling frequency (Hz)
wp = 5000; % passband frequency
ws = 7000; % stopband frequency
n = 6; % filter order = 2*n = 12
w1 = (2 * wp)/fs;
w2 = (2 * ws)/fs;
wn = [w1, w2];
[b, a] = butter(n, wn, 'stop');

% plot magnitude response
w = 0:0.01:pi;
[h, om] = freqz(b, a, w);
m = 20*log10(abs(h));

figure, plot(om/pi * (fs/2), m);
% axis([0 0.1 -1 1])
ylabel('Gain (dB)');
xlabel('Frequency (Hz)');

% create signal and check response
ts = 1/fs;
t = 0:ts:1;
f1 = 6000;
f2 = 2000;
% x = sin(2*pi*f2*t);
x = 0.5*sin(2*pi*f1*t)+0.5*sin(2*pi*f2*t);
figure, plot(t, x, ':r');
axis([0 0.005 -2.2 2.2])
hold on
y = filter(b, a, x);
plot(t, y, 'b');

% write data to file
fileID = fopen('data_2k.txt','w');
fprintf(fileID, '%d\n', round(x*(2^20)));
fclose(fileID);

fileID = fopen('data_a_b.txt','w');
fprintf(fileID, '%d\n', round(a*(2^20)));
fprintf(fileID, '\n');
fprintf(fileID, '%d\n', round(b*(2^20)));
fclose(fileID);
```
I'm very confused about this.

**Comment by fhrgithub** [comment]
I'm sorry to bother you. I find that I mistake you with another person. You use a low-pass filter, while he uses a band-stop filter.
Again, my sincere apologies.
